# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5422ebd95f9d72b75f0b0501ad8f5e9459514c1d08d2960d71d3c93e746ee5f1c251ec52db1f34e5b10a94b3a94efb89ec507410f6db84a474496a846c3cd9f5

test:
  secret_key_base: 1ee151af5a1f9aa78be7548e22c5d6e8e969187850a03653cf7405c764fab91b4985859cb54745aca50ee4080b56b8c3dbf18d83ef1dadd7898fdd42313bc094

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
